name: ARM64 Build and Release

on:
  push:
    tags: ['v*']  # 仅在打标签时触发（如 v1.0.0）

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # 设置 ARM64 构建环境
      - name: Set up QEMU for ARM64
        uses: docker/setup-qemu-action@v3
        with:
          platforms: arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # 获取版本号（去掉标签的 'v' 前缀）
      - name: Get version
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      # 安装 ARM64 交叉编译工具链（如需原生编译可跳过）
      - name: Install ARM64 toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

      # 执行 ARM64 构建
      - name: Build for ARM64
        run: |
          make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- VERSION=$VERSION

      # 打包构建产物
      - name: Package artifacts
        run: |
          mkdir -p release
          tar -czvf release/pagemap-${VERSION}-linux-arm64.tar.gz -C output .

      # 创建或更新 Release（自动处理重复标签）
      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ env.VERSION }}
          name: "ARM64 Build v${{ env.VERSION }}"
          files: |
            release/*.tar.gz
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
